name: extra_staff
description: A Banking project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.1.4
  mime: ^1.0.0
  http: ^0.13.3
  local_auth: ^2.1.3
  loading_overlay: ^0.3.0
  image_picker: ^1.0.2
  flutter_signature_pad: ^3.0.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.8
  intl: ^0.18.1
  dots_indicator: ^3.0.0
  flutter_keyboard_visibility: ^5.0.3
  pin_code_fields: ^8.0.1
  geolocator: ^10.0.0
  flutter_html: ^3.0.0-beta.2
  device_info: ^2.0.2
  file_picker: ^5.2.10
  url_launcher: ^6.1.5
  sentry_flutter: ^6.22.0
  app_tracking_transparency: ^2.0.2+4
  image_picker_web: any
  device_info_plus: any
  dart_ipify: ^1.1.1
  roundcheckbox: ^2.0.5
  flutter_svg: ^1.1.6
  flutter_advanced_switch: ^3.0.1
  adaptive_theme: ^3.2.1
  flick_video_player: ^0.5.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  accordion: ^2.5.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  table_calendar: ^3.0.8
  flutter_math_fork: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/images/v2/
    

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/fonts/Poppins-ExtraLight.ttf
          weight: 200
